feat: support i18n
peanut996/CloudflareWarpSpeedTest pull request #19
Opened 2024-06-12 16:32 UTC by xrz-cloud

1. 对国际化提供了支持(en_US及zh_CN)
2. 修改了 用例 函数的逻辑

## TODO

1. tasks、utils中的文本国际化

2024-06-12 16:40 UTC, peanut996 commented
这样的话 就要把locale 文件打到binary 里面才行吧。

2024-06-13 03:06 UTC, peanut996 commented
```go
// 声明配置资源
//go:embed locale/*.toml
var localeFiles embed.FS


// init 函数中读取对应资源
loadMessageFile := func(file string) {
data, err := localeFiles.ReadFile(file)
if err != nil {
	fmt.Printf("Failed to read embedded file: %v\n", err)
	return
}
if _, err := bundle.ParseMessageFileBytes(data, file); err != nil {
	fmt.Printf("Failed to parse message file: %v\n", err)
}
}
loadMessageFile("locale/i18n.en.toml")
loadMessageFile("locale/i18n.zh.toml")


```

2024-06-13 14:02 UTC, peanut996 commented on locale/embed_i18n.go
> +	bundle.LoadMessageFileFS(LocaleFS, path+".zh.toml")
go fmt 格式化一下呢

2024-06-13 14:04 UTC, peanut996 commented on locale/embed_i18n.go
> +func Init_i18n(path string) *i18n.Localizer {
文件名就叫i18n.go 呗 和包名保持一致

2024-06-13 14:10 UTC, peanut996 commented on task/warping.go
> +		bar:     utils.NewBar(len(ips), i18n.Query_i18n(localizer_wrping, "Available:"), ""),
"Available:" 也要国际化吧

2024-06-13 14:33 UTC, xrz-cloud commented
现在有~12MB了

2024-06-13 14:42 UTC, xrz-cloud commented on locale/embed_i18n.go
> +	bundle.LoadMessageFileFS(LocaleFS, path+".zh.toml")
我这边貌似`go fmt`出来就是这样，估计是默认设置的问题

2024-06-13 14:45 UTC, xrz-cloud commented on task/warping.go
> +		bar:     utils.NewBar(len(ips), i18n.Query_i18n(localizer_wrping, "Available:"), ""),
这里是国际化的

2024-06-13 15:13 UTC, peanut996 requested changes

2024-06-13 15:13 UTC, peanut996 commented on locale/task/warping.en.toml
话说这里的Key 不能给变量名吗 就类似Main那个文件里面的

2024-06-13 15:27 UTC, xrz-cloud commented on locale/task/warping.en.toml
感觉有点命名困难症，难得想合适的变量名，干脆就贴上原本的文本，直观一些。
不过可以的话，你可以改一下合适的变量名。

2024-06-14 04:42 UTC, peanut996 commented
我开了一个新分支 develop 这个pr先合并到这个分支上， 搞完再合并回master

2024-06-14 04:43 UTC, merged